### PR TITLE
Done redo_update_rotati_address (Note: Ruby version was changed, but …

### PR DESCRIPTION
**Pull request by PirunSeng**
…it seems no problem after running test.)

### CODE REVIEW

**Comment by jensendarren** [comment]
Thanks. I've merged this change in and deployed already.

**Comment by PirunSeng** [comment]
Excuse me Sir,
I'm afraid there is something error with the map in iframe. 
I just replace the url in the iframe src, but I don't know why it doesn't show the new url map.
I'll fix this soon.

**Comment by jensendarren** [comment]
Yea, I see that. Please make another branch (from 'source') and see if you
can fix that (using the correct office location).

**Comment by PirunSeng** [comment]
Ok! I've just found the solution by using google map api. It works well in local, and I hope it will still work on production. I think I can pull a new request this evening. :)

**Comment by jensendarren** [comment]
OK thank you Pirun!

**Pull request merged**
