### PR TITLE
add_canada_address

### PR DESCRIPTION
**Pull request by PirunSeng**
I've already added Rotati Canada Address in footer and map on Contact page.
Please let me know if it is okay, or it need to be improved.

### CODE REVIEW

**Comment by jensendarren** [comment]
@PirunSeng thanks!

**Comment by PirunSeng** [comment]
You're welcome, Sir!
I hope there won't be any problems :D

**Comment by jensendarren** [comment]
Cool. I made a minor adjustment to separate the two addresses but nothing too much. I've deployed the change now: http://www.rotati.com/contact/

**Comment by PirunSeng** [comment]
I checked it.
It's cool that it works fine. :)

**Pull request merged**
